apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: aa-workflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs:
        - job1
jobs:
  job1:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
