apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call other org

on:
  workflow_dispatch:

jobs:
  call:
    uses: gmaxey/subworkflows/.cloudbees/workflows/deploy.yaml
    vars: inherit
    with:
        artifactName: "asdf"
        artifactVersion: "asdf2"
