apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call other org

on:
  workflow_dispatch:

jobs:
  call:
    uses: https://github.com/gmaxey/subworkflows/blob/main/.cloudbees/workflows/deploy.yaml
    with:
        artifactName: "asdf"
        artifactVersion: "asdf2"
