apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: inheritance tests
on:

  workflow_dispatch:
    inputs:
      targetenv:
        type: string
        default: ''
jobs:
  testcall:
    uses: mluzcabrera/reusableworkflowsrepo/.cloudbees/workflows/reusable.yaml
    secrets: inherit
    vars: inherit
    with:
      targetenv: ${{ inputs.targetenv }}
