apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Param environment in parallel exists
on:
  push:
    branches:
      - main
jobs:
  testcall:
    uses: mluzcabrera/reusableworkflowsrepo/.cloudbees/workflows/reusable.yaml
    secrets: inherit
    vars: inherit
    # with:
    #   targetenv: ${{ inputs.targetenv }}
    

