apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Param environment in parallel exists
on:
  workflow_dispatch:
    inputs:
      targetenv:
        type: string
        required: true
        default: environment_mlcb_test_param
jobs:

  testcall:
    uses: mluzcabrera/reusableworkflowsrepo/.cloudbees/workflows/reusable.yaml
    whatever:
      what: ever
    with:
      targetenv: ${{ inputs.targetenv }}
    

